
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
{

}
import 'bootstrap/dist/css/bootstrap.min.css';

import { cn } from "@/lib/utils"
import { Navbar } from "react-bootstrap";
import FooterComponent from "./Component/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>{children}</body>
    
    </html>
  );
}
