
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
{

}
import 'bootstrap/dist/css/bootstrap.min.css';

import { cn } from "@/lib/utils"

import FooterComponent from "./Component/Footer";
import NavbarComponent from "./Component/Navbar";



export const metadata: Metadata = {
  title: "Nexcent",
  description: "Generated by create next app",
};
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
       <NavbarComponent/>
        {children}
        
      <FooterComponent/>
      </body>
    
    </html>
  );
}
